### ISSUE TITLE
Undefined factor of \[Mu]H[1]

### ISSUE THREAD

**Issue by og113** [DR-algo/DRalgo#15]
Running the example xsm.m, integrating out the soft-scale singlet leads to an unexplained factor of `\[Mu]H[1]` in the Higgs self-coupling. The relevant commands in the file are
```
PerformDRsoft[{5}];
PrintCouplingsUS[]
```
The quantity `\[Mu]H[1]` appears not to be defined anywhere in the file, nor can I find it documented.

I am using the current version of the main branch, Mathematica 13.0 and Ubuntu 22.

**Comment by AndreasEkstedt** [comment]
Dear og113, thank you for bringing this to our attention. This is indeed a bug. The bug should now be fixed. Please let us know if you have any further problems.

Kind Regards,
Andreas
