### ISSUE TITLE
Mode->0 in ImportModelDRalgo[] produces errors and inconsistent matching results

### ISSUE THREAD

**Issue by niemilau** [DR-algo/DRalgo#21]
Reproduce: Run examples/sm.m with Mode->0 in the call to ImportModelDRalgo[].

Output:
![Screenshot from 2023-11-30 17-51-26](https://github.com/DR-algo/DRalgo/assets/113029612/c565d6fb-f160-4c92-9881-8f3b16a770ad)

Version info: see issue #20

**Comment by AndreasEkstedt** [comment]
Hi Lauri. Mode->0 means that only thermal masses (to leading-order) are calculated, so what you see when trying to print couplings, without using Mode->1 or higher, should indeed not to be trusted.

**Comment by niemilau** [comment]
I see, is there any way to get all hard-scale parameters matched at leading order? The couplings are of course trivial, but I'm building an automated export pipeline and want to avoid manually writing them down (my model has a lot of parameters).

**Comment by AndreasEkstedt** [comment]
It depends on how you want to export the effective parameters, and what information you need. Scalar and Debye masses and be found like usual mode->0. And if you want to export the names of, say all quartics, you can use

\[Lambda]4//Normal//Variables

And similar for all gauge couplings

Join[gvvv//Normal//Variables,gvss//Normal//Variables,gvff//Normal//Variables]//DeleteDuplicates
