### ISSUE TITLE
Normalization4D->True gives inconsistent and repeated matching of gauge couplings

### ISSUE THREAD

**Issue by niemilau** [DR-algo/DRalgo#22]
![Screenshot from 2023-12-01 11-28-58](https://github.com/DR-algo/DRalgo/assets/113029612/839a6bcf-e406-4f8a-a943-032f21885ab5)

Reproduce: Run examples/sm.m with Normalization4D->True in the call to ImportModelDRalgo[].

The output of PrintCouplings[] then has two different entries for gw3d matching, see the screenshot above. The gs3d matching also has wrong powers of T.

My versions:
Mathematica 13.0.1.0
DRalgo 1.1 (including Nov 27th commits from main branch)

**Comment by AndreasEkstedt** [comment]
Hi Lauri, yes this is indeed an issue with Normalization4D->True that will be fixed in the next update.
