### ISSUE TITLE
Installation instructions unclear

### ISSUE THREAD

**Issue by Subtlesplendor** [DR-algo/DRalgo#6]
I cloned the package from the main branch and it automatically gave the folder the name DRalgo-main. I tried copying that file into Applications but that did not work. It only worked when I renamed the folder to DRalgo.

More details:

When installing DRalgo, the manual (section 2.1: Installation) instructs us to 

> The current version of DRalgo, 1.0, is installed by placing all the source files either in the
applications folder Mathematica/Applications ...

And the README similarly states:

> To load DRalgo, place the package in the $UserBaseDirectory/Applications folder ...

(These folders are equivalent.)

Maybe it works to put all the source files directly into the Applications folder, but that is not really advisable since it will clutter the folder. 

As I stated above, one thing that does not work is to place the package in a subfolder with an arbitrary name in Applications. It needs to have the particular name DRalgo.

**Comment by Subtlesplendor** [comment]
I also tested with the official 1.0 beta release. In this case the folder was called "DRalgo-1.0-beta". This did not work and also required renaming the folder.

**Comment by pschicho** [comment]
Thanks for bringing this to our attention. In fact, one should place the content of the package folder in `$UserBaseDirectory/Applications/DRalgo` to fix this -- this is only an issue if one loads zipped folders which are named after the corresponding releases. A clarification will be updated in the future draft and `README.md`.
